steps:
  # Сборка Docker образа
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "REGION-docker.pkg.dev/$PROJECT_ID/larp-bugle-repo/larp-bugle-bot",
        ".",
      ]

  # Отправка образа в Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "REGION-docker.pkg.dev/$PROJECT_ID/larp-bugle-repo/larp-bugle-bot",
      ]

# Настройки логирования
options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

# Настройки для развертывания
images:
  - "REGION-docker.pkg.dev/$PROJECT_ID/larp-bugle-repo/larp-bugle-bot"
