steps:
  # Создание репозитория в Artifact Registry (если не существует)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud artifacts repositories create larp-bugle-repo \
          --repository-format=docker \
          --location=us-central1 \
          --description="Docker repository for larp-bugle-bot" \
          --quiet || echo "Repository already exists"

  # Настройка аутентификации Docker
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

  # Сборка Docker образа
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/larp-bugle-repo/larp-bugle-bot",
        ".",
      ]

  # Отправка образа в Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/larp-bugle-repo/larp-bugle-bot",
      ]

# Настройки логирования
options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

# Настройки для развертывания
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/larp-bugle-repo/larp-bugle-bot"
